services:
  backend:
    build:
      target: dev
    volumes:
      - ./neydi-be:/app

  frontend:
    build:
      target: dev
    environment:
      NUXT_PUBLIC_API_BASE: /api
      NUXT_API_PROXY_TARGET: http://backend:8000
    volumes:
      - ./neydi-fe:/app
      - /app/node_modules
      - /app/.pnpm-store
      - /app/.nuxt