name: backend tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: neydi-be/requirements-test.txt

      - name: Install dependencies
        run: pip install -r requirements-test.txt
        working-directory: neydi-be

      - name: Run tests
        run: python -m pytest tests/ -v --durations=10
        working-directory: neydi-be
